# Generated by Django 3.1.7 on 2021-03-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wybor',
            new_name='Choice',
        ),
    ]
